// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACSwcI6K4LGryB4um2SSLiYDNrnPR_D6U',
    appId: '1:1034977453939:web:9a22e14298d03895b70706',
    messagingSenderId: '1034977453939',
    projectId: 'mindwell-d7b89',
    authDomain: 'mindwell-d7b89.firebaseapp.com',
    storageBucket: 'mindwell-d7b89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRG6ofj8ztp1WRbZvjCQXalcT0V0y-seY',
    appId: '1:1034977453939:android:99247964a7838960b70706',
    messagingSenderId: '1034977453939',
    projectId: 'mindwell-d7b89',
    storageBucket: 'mindwell-d7b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC47z4iS_Zj1KX8tVa6Oga_6C1yc7Iw9wY',
    appId: '1:1034977453939:ios:ed3405fdeaf2fbe2b70706',
    messagingSenderId: '1034977453939',
    projectId: 'mindwell-d7b89',
    storageBucket: 'mindwell-d7b89.firebasestorage.app',
    iosBundleId: 'com.example.gradproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC47z4iS_Zj1KX8tVa6Oga_6C1yc7Iw9wY',
    appId: '1:1034977453939:ios:ed3405fdeaf2fbe2b70706',
    messagingSenderId: '1034977453939',
    projectId: 'mindwell-d7b89',
    storageBucket: 'mindwell-d7b89.firebasestorage.app',
    iosBundleId: 'com.example.gradproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACSwcI6K4LGryB4um2SSLiYDNrnPR_D6U',
    appId: '1:1034977453939:web:6899ead26525ed61b70706',
    messagingSenderId: '1034977453939',
    projectId: 'mindwell-d7b89',
    authDomain: 'mindwell-d7b89.firebaseapp.com',
    storageBucket: 'mindwell-d7b89.firebasestorage.app',
  );
}
